name: Update README cards

on:
  schedule:
    - cron: "0 02 * * 0" # Runs once a week at two am
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=github_dark_dimmed&rank_icon=github&count_private=true&card_width=320
          path: profile/stats.svg
          token: ${{ secrets.GRS }}

      - name: Generate language card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&theme=github_dark_dimmed&exclude_repo=hugo-blox-builder,hugo-theme-documentation,djps.github.io&card_width=320
          path: profile/lang.svg
          token: ${{ secrets.GRS }}

      - name: Generate pin card for pyKZK
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=pyKZK&layout=compact&theme=github_dark_dimmed
          path: profile/pyKZK.svg
          token: ${{ secrets.GRS }}

      - name: Generate pin card for streamlit-transcranial
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=streamlit-transcranial&layout=compact&theme=github_dark_dimmed
          path: profile/streamlit.svg
          token: ${{ secrets.GRS }}   

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
          
