name: Update README cards weekly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 02 * * 0" # Runs once a week at two am

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=github_dark_dimmed&rank_icon=github&count_private=true&card_width=437&disable_animations=true
          path: profile/stats.svg
          token: ${{ secrets.GRS }}

      - name: Generate language card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&theme=github_dark_dimmed&exclude_repo=hugo-blox-builder,hugo-theme-documentation,djps.github.io&card_width=437&disable_animations=true
          path: profile/lang.svg
          token: ${{ secrets.GRS }}

      - name: Generate pin card for pyKZK
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=pyKZK&layout=default&theme=github_dark_dimmed&show_owner=false&description_lines_count=2
          path: profile/pyKZK.svg
          token: ${{ secrets.GRS }}

      - name: Generate pin card for streamlit-transcranial
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=streamlit-transcranial&layout=default&theme=github_dark_dimmed&show_owner=false&description_lines_count=2
          path: profile/streamlit.svg
          token: ${{ secrets.GRS }}   

      - name: Generate pin card for homoclinic-orbits
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=homoclinic-orbits&layout=default&theme=github_dark_dimmed&show_owner=false&description_lines_count=2
          path: profile/homoclinic.svg
          token: ${{ secrets.GRS }}   

      - name: Generate pin card for thesis
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=Thesis&layout=default&theme=github_dark_dimmed&show_owner=false&description_lines_count=2
          path: profile/thesis.svg
          token: ${{ secrets.GRS }}   

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit --allow-empty -m "Update README weekly cards" || exit 0
          git push
          






