name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=github_dark_dimmed
          path: profile/stats.svg
          token: ${{ secrets.GRS }}

      - name: Generate language card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&theme=github_dark_dimmed
          path: profile/lang.svg
          token: ${{ secrets.GRS }}
          
      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master 
          folder: 'profile'
          repository-name: djps/homepage
          target-folder: static/uploads/git-data
          git-config-name: djps
          token: ${{ secrets.GRS }}
          commit-message: 'update githun stats on homepage'
          single-commit: false
          clean: true
          silent: false
